- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: checking
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user
    ansible.builtin.debug:
     msg: " {{ user }}"