- name: packages install
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: loop install
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
    - nginx
    - mysql 